FROM node:16 AS build

RUN mkdir -p /usr/src/my-store

WORKDIR /usr/src/my-store

ARG NODE_ENV
ARG DATABASE_URL
ARG API_KEY
ARG JWT_SECRET
ARG SMTP_EMAIL
ARG SMTP_PASSWORD

ENV NODE_ENV=$NODE_ENV
ENV DATABASE_URL=$DATABASE_URL
ENV API_KEY=$API_KEY
ENV JWT_SECRET=$JWT_SECRET
ENV SMTP_EMAIL=$SMTP_EMAIL
ENV SMTP_PASSWORD=$SMTP_PASSWORD

COPY package*.json ./
RUN npm ci

COPY . .

RUN npm run migrations:run

EXPOSE 8080

CMD ["npm", "start"]
